spring:
  profiles:
    active: prod
  jpa:
      properties:
        hibernate:
          hbm2ddl:
            auto: update
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          show-sql: true
          hibernate:
                naming:
                  physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl